# Generated by Django 5.0.4 on 2024-05-08 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chronicle', '0003_alter_record_options_record_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='date_happened',
            field=models.DateField(blank=True, null=True, verbose_name='Дата события'),
        ),
    ]
